#72
Lixard/matcher pull request #25
Opened 2021-09-13 21:04 UTC by Formeyz

Добавил данные

2021-09-13 21:05 UTC, PatcH11 commented
ОН ПАРОЛИ НЕ ЗАХЕШИРОВАЛ!!!!!!!!

2021-09-13 21:07 UTC, Maximqalol commented
ЕБАКЛАК!!!1

2021-09-14 09:06 UTC, Lixard requested changes

2021-09-14 09:06 UTC, Lixard commented on db_migrations/changesets/master/M-006.sql
> +INSERT INTO matcher.users (login, password, first_name, last_name, second_name, email, phone) VALUES ('patch11k','123','Николай', 'Евсюков', 'Эдуардович',  'paj@gmail.com', 88005553531);
Пароли хешить нада

2021-09-18 21:34 UTC, Lixard approved these changes
Надеюсь ты тестил работоспособность этих аккаунтов)

2021-09-19 09:18 UTC, merged