#41 Fix form registration
Lixard/matcher pull request #26
Opened 2021-09-14 17:56 UTC by DarkRacer

Add hint if student don't found University and rename fields in registration page for student

2021-09-14 18:40 UTC, Lixard requested changes

2021-09-14 18:40 UTC, Lixard commented on backend/src/main/resources/application.yaml
> +    password: 54321
И зачем? Если тебе нужны какие-то локальные настройки, то проставляй их в таске рана в идее. 
![image](https://user-images.githubusercontent.com/51443500/133315045-5dedc60a-b290-47e8-a1e8-0812d0846fbc.png)

2021-09-17 16:55 UTC, DarkRacer commented on backend/src/main/resources/application.yaml
> +    password: 54321
Исправил

2021-09-18 21:35 UTC, Lixard approved these changes

2021-09-19 07:57 UTC, merged