#57 Add functionality for user interaction with projects
Lixard/matcher pull request #28
Opened 2021-09-19 19:15 UTC by DarkRacer

2021-09-19 21:25 UTC, Lixard requested changes

2021-09-19 21:25 UTC, Lixard commented on backend/data/src/main/java/ru/matcher/data/model/Project.java
> +    @ManyToOne(targetEntity = Organization.class)
Зачем ты эти таргет энтити суешь?) Ониж ни на что не влияют

2021-09-19 21:25 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/ProjectDto.java
> +    private Integer organizationId;
Еще раз, важное правило: все, что может быть примитивом, является примитивом, ЕСЛИ только оно не`nullable`. Если `organizationId` в какой-то ситуации может быть null, тогда используем объекты

2021-09-19 21:25 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/ProjectDto.java
> +    private Integer organizationId;
Я не буду везде треды открывать на счет этого (а тут их много), но на будущее запомни

2021-09-19 21:25 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserServiceImpl.class);
Как это `UserServiceImpl.class` если это `ProjectParticipationServiceImpl.class`? Попался копипастер)

2021-09-19 21:25 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +        logger.info("projectParticipationBuilder: {}", projectParticipationBuilder.build());
Можно нормальные сообщения о логировании? например `User(id = takoi-to) subscribes to project(id = takoi-to)`

2021-09-19 21:25 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +        logger.info("projectParticipationBuilder: {}", projectParticipationBuilder.build());
Потому что эта штука вообще нам ни о чем не говорит

2021-09-19 21:25 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectServiceImpl.java
> +        logger.info("projectParticipationBuilder: {}", projectParticipationBuilder.build());
Тут то же с сообщением логирования

2021-09-19 21:25 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/ProjectController.java
> +    }
Погоди, всм? У нас нельзя подписать другого человека на проект, у нас каждый сам подписывается. Зачем тогда мы передаем `userId`? Дерни из authUser его

2021-09-19 21:25 UTC, Lixard commented on frontend/src/app/project/project-page/project-page.component.ts
> +      window.location.reload();
Вот ты грязный тип конечно, а без релоада на каждый пук слабо?)

2021-09-19 21:32 UTC, DarkRacer commented on frontend/src/app/project/project-page/project-page.component.ts
> +      window.location.reload();
везде нужен релоад))

2021-09-19 21:34 UTC, Lixard commented on frontend/src/app/project/project-page/project-page.component.ts
> +      window.location.reload();
Нужен (не хотел особо думать поэтому сделал так)?))) Как говорится, это будет на твоей совести 😈

2021-09-20 20:08 UTC, DarkRacer commented on backend/data/src/main/java/ru/matcher/data/model/Project.java
> +    @ManyToOne(targetEntity = Organization.class)
JPA ругается иначе

2021-09-21 11:23 UTC, Lixard requested changes

2021-09-21 11:23 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +    private static final Logger logger = LoggerFactory.getLogger(ProjectServiceImpl.class);
Класс называется `ProjectParticipationServiceImpl`. Ты можешь в логгер передать его же?? Либо можешь сделать `this.getClass()`, в теории должно сработать

2021-09-21 11:23 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +        logger.info("User({}) subscribe to project project({})", currentUser.getId(), projectId);
Просто напиши "User(id = {}) subscribes to the project(id = {})"

2021-09-21 20:06 UTC, Lixard requested changes
Чел)

2021-09-21 20:06 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +        logger.info("User(id = {}) subscribe to project project(id = {})", currentUser.getId(), projectId);
Блин, чел, ну я же написал прям слово в слово что написать.
1. subscribe**s**
2. Слово project дважды написано (зачем?)

2021-09-21 20:25 UTC, Lixard approved these changes
Наконец-то 🗿

2021-09-21 21:34 UTC, merged

2021-10-03 18:26 UTC, Lixard commented
![](https://github.trello.services/images/mini-trello-icon.png) [Функционал взаимодействия пользователей с проектами](https://trello.com/c/N1Mt0rWZ/57-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB-%D0%B2%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9-%D1%81-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0%D0%BC%D0%B8)

2021-10-03 18:26 UTC, Lixard commented
![](https://github.trello.services/images/mini-trello-icon.png) [Функционал взаимодействия пользователей с проектами](https://trello.com/c/N1Mt0rWZ/57-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB-%D0%B2%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9-%D1%81-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0%D0%BC%D0%B8)