#67
Lixard/matcher pull request #30
Opened 2021-09-26 20:52 UTC by Maximqalol

2021-09-27 18:36 UTC, Lixard requested changes
Чуть-чуть причесать и можно будет лить

2021-09-27 18:36 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +    }
1. У нас конечно апишки и так почти без валидации, но тут будет грязновато. Добавь проверочку является ли текущий юзер админом конкретного проекта, и если нет то кидай 403 (менять роли могут только админы проектов)
2. Логгернуть бы - можно что-то типа `Admin(id = {}) changed user's(id = {}) role in the project(id = {}) from '{}' to '{}'`

2021-09-27 18:36 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectServiceImpl.java
> +        return projectDtos;
А до этого чем было хуже?)

2021-09-27 18:38 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectParticipationServiceImpl.java
> +    }
И `@Transactional` можно повесить, лишним не будет. Так как изменения в бд льются, хоть и единичным запросом, но никто не застрахован от последствий масштабирования функционала 😈

2021-09-27 18:43 UTC, PatcH11 commented
> Чуть-чуть причесать и можно будет лить

Комов хороший парикмахер😯😯😎👍

2021-09-30 23:39 UTC, Lixard approved these changes

2021-09-30 23:45 UTC, merged