#33
Lixard/matcher pull request #4
Opened 2020-11-15 02:01 UTC by DarkRacer

* Написал конвертер enum для таблицы org_types и добавил записи с Enum значениями в БД

2020-11-15 02:02 UTC, DarkRacer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Написать конвертер enum для таблицы org_types и добавить записи с Enum значениями в БД](https://trello.com/c/K7Elw2hf/33-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%BA%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B5%D1%80-enum-%D0%B4%D0%BB%D1%8F-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B-orgtypes-%D0%B8-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8-%D1%81-enum-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8-%D0%B2-%D0%B1%D0%B4)

2020-11-16 06:11 UTC, Lixard requested changes
Как Коля доделает свои дела - протестируй

2020-11-16 06:11 UTC, Lixard commented on db_migrations/changesets/rollback/M-002.rollback.sql
> +DELETE * FROM matcher.org_types WHERE org_type_id = 2;
`DELETE FROM` синтаксис (без звездочки)

2020-11-22 11:23 UTC, Lixard requested changes
Поправь то, что я отметил и проверь работоспособность, @PatcH11 дописал сервисы.

2020-11-22 11:23 UTC, Lixard commented on backend/commons/build.gradle
> +    annotationProcessor "org.projectlombok:lombok:$lombok_ver"
Убери ломбок, мы от него отказались по итогу

2020-11-22 11:23 UTC, Lixard commented on db_migrations/changesets/master-changelog.yml
> +            relativeToChangelogFile: true
Подтяни последние правки и посмотри какой айди у твоей миграции будет теперь. Потому что @PatcH11 делал миграцию тоже.

2020-11-22 11:23 UTC, Lixard commented on backend/data/src/main/java/ru/matcher/data/converter/EnumConverterOrganizationType.java
> +        return null;
Нет, метод с поиском конкретного аттрибута по айдишнику тебе нужно было сделать в самом енаме. Метод будет статическим и выглядеть что-то типа:
```java
  public static ParameterType getValue(Integer value) {
    if (value == null) {
      return null;
    }
    for (final ParameterType type : ParameterType.values()) {
      if (value.equals(type.getId())) {
        return type;
      }
    }
    return null;
  }

```

2020-11-22 11:23 UTC, Lixard commented on backend/commons/src/main/java/ru/matcher/commons/OrganizationTypeEnum.java
> +public enum OrganizationTypeEnum {
не надо в названии подписывать Enum, все и так в курсе, они и так достаточно однозначно описаны значком
![image](https://user-images.githubusercontent.com/51443500/99902310-f0838100-2ccd-11eb-9918-5d80dfd6b43a.png)

2020-11-22 11:23 UTC, Lixard commented on backend/commons/src/main/java/ru/matcher/commons/OrganizationTypeEnum.java
> +public enum OrganizationTypeEnum {
Тип класса подписывается разве что у интерфейсов (буква `I` вначале), и делается это для того, чтобы все интерфейсы в пекедже лежали рядом друг с другом

2020-11-22 11:25 UTC, Lixard commented on db_migrations/changesets/master-changelog.yml
> +            relativeToChangelogFile: true
Гитхаб, впрочем, сам об этом тебе сообщает и не даст замержить в `dev`.
![image](https://user-images.githubusercontent.com/51443500/99902389-87503d80-2cce-11eb-96b9-7fd3d6387bf5.png)

2020-11-23 06:55 UTC, Lixard commented on backend/data/src/main/java/ru/matcher/data/converter/EnumConverterOrganizationType.java
> +        return null;
Лучше всего это еще в Optional запихать

2021-02-22 18:46 UTC, closed without merging