#85
Lixard/matcher pull request #42
Opened 2021-11-11 08:16 UTC by Maximqalol

added file system

2021-11-11 21:10 UTC, Lixard requested changes
И общее замечание: сделай пожалуйста нормальные rest пути у файлов.
То есть:
файлы какого-то проекта: `/projects/{projectId}/files`
загрузка файла `/projects/{projectId}/files/{fileId}`
и тд.

2021-11-11 21:10 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/FileServiceImpl.java
> +}
А зачем тебе это вообще?

2021-11-11 21:10 UTC, Lixard commented on backend/data/src/main/java/ru/matcher/data/model/File.java
> +import javax.persistence.*;
Так лучше не делай, тебе вряд ли нужен весь package. Поставь в IntelliJ Idea настройку, чтоб она не запаковывала импорты в *

2021-11-11 21:10 UTC, Lixard commented on backend/data/src/main/java/ru/matcher/data/model/Project.java
> +import javax.persistence.*;
Тут тоже

2021-11-11 21:10 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +    }
Погоди, не понял. А зачем тебе тогда апишка которая выше? Если у тебя есть апишка для нормального скачивания файла?

2021-11-11 21:58 UTC, Lixard commented
![](https://github.trello.services/images/mini-trello-icon.png) [Создание хранилища файлов у проектов](https://trello.com/c/Ws3zKUCz/85-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D1%83-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BE%D0%B2)

2021-11-13 14:16 UTC, Lixard requested changes

2021-11-13 14:16 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +import org.springframework.web.bind.annotation.*;
Не все звездочки убрал

2021-11-13 14:16 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/ProjectStruct.java
> +import ru.matcher.data.model.*;
*

2021-11-13 14:16 UTC, Lixard commented on backend/src/main/resources/application.yaml
> +
этот отступ в конфиге лишний

2021-11-13 14:39 UTC, Lixard requested changes

2021-11-13 14:39 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +    @PostMapping("/files/project/{projectId}/create")
POST `/projects/{projectId}/files`

2021-11-13 14:39 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +    public ResponseEntity<byte[]> downloadFileById(@PathVariable Integer fileId) {
В параметры projectId то добавь, и желательно оставь коммент в методе: `// TODO access rights`

2021-11-15 14:51 UTC, Lixard requested changes
Ну и еще пачку тебе 😈

2021-11-15 14:51 UTC, Lixard commented on backend/data/src/main/java/ru/matcher/data/model/File.java
> +    private Date createdAt;
1. `java.util.Date` - легаси. В 21 веке стоит использовать любой класс из `java.time`.
2. Лучше `createdAt` представлять как дату с временем, а не просто дату.

2021-11-15 14:51 UTC, Lixard commented on backend/data/src/main/java/ru/matcher/data/repository/ProjectRepository.java
> +    Project findProjectById(@Param("projectId") int projectId);
Этот метод не имеет смысла, так как в `ProjectRepository` он уже реализован, называется `findById`

2021-11-15 14:51 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/IFileService.java
> +    FileDto create(MultipartFile file, int projectId) throws IOException;
Не надо эксепшен выкидывать так высоко, обработай его в этом же сервисе через try-catch

2021-11-15 14:51 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/FileServiceImpl.java
> +    }
Какой смысл тут от `@Transactional` если операция одна и она атомарна?)

2021-11-15 14:51 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/ProjectServiceImpl.java
>          return projectStruct.toDto(project);
Вот эти все преобразования лучше прятать на уровень мапстракта, в сервисах перекладывать одно в другое ни к чему.

2021-11-15 14:51 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +    }
Зачем тебе вообще такая апишка? Нет никакого смысла отдавать все файлы кому либо

2021-11-15 14:51 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +    @DeleteMapping("/files/{id}")
Путь, пожалуйста, как у остальных методов `/projects/...`

2021-11-15 17:16 UTC, Lixard approved these changes
последнее глянь и можешь заливать

2021-11-15 17:16 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +    public FileDto createFile(@RequestParam("file") MultipartFile file, @PathVariable Integer projectId) throws IOException {
а чо тут за эксепшен? тыж вроде переписал метод

2021-11-15 17:17 UTC, Maximqalol commented on backend/src/main/java/ru/matcher/rest/controller/FileController.java
> +    public FileDto createFile(@RequestParam("file") MultipartFile file, @PathVariable Integer projectId) throws IOException {
я забыл просто его стереть (он серым горел)

2021-11-15 17:20 UTC, merged