#35
Lixard/matcher pull request #5
Opened 2020-11-17 18:35 UTC by PatcH11

2020-11-17 18:38 UTC, PatcH11 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сущности, Dto, Мапперы, Интерфейсы сервисов и их имплементации по каждой сущности](https://trello.com/c/1ykbusMi/35-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8-dto-%D0%BC%D0%B0%D0%BF%D0%BF%D0%B5%D1%80%D1%8B-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D1%8B-%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%BE%D0%B2-%D0%B8-%D0%B8%D1%85-%D0%B8%D0%BC%D0%BF%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE-%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%B9-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8)

2020-11-17 23:56 UTC, Lixard requested changes
Поправь то что я написал и в смежных классах тоже, не только где отмечено.
Например, раз тред стоит на `createOrUpdate`, то его надо поменять во всех остальных классах. 🥇

2020-11-17 23:56 UTC, Lixard commented on backend/services/build.gradle
> +    implementation "org.mapstruct:mapstruct:$mapstruct_ver"
Для мапстракта еще annotationProcessor нужен, иначе они начнут драться с ломбоком в определенных ситуациях

2020-11-17 23:56 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/FileDto.java
> +    private byte[] data;
Одна дтошка не подойдет для всех случаев.
Например возвращая список файлов тебе не нужно возвращать сами файлы (дату), тебе нужно все остальное (+ желательно урл для загрузки, но это потом).
Сделай отдельно dto'шку для получения одного файла(которая сейчас уже есть) и одну для того чтобы делать из нее список (без даты).
Так на самом деле во многих случаях могут быть отдельно дтошки на все случаи жизни:create, get, update, delete По всем методам апи короче.

2020-11-17 23:56 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/FileDto.java
> +public class FileDto {
И еще, поменяй плиз названия File на Picture везде в проекте у нас, я потом миграцию сделаю чтобы это поменять в бд. Лучше пусть аватарки лежат в отдельной таблице.

2020-11-17 23:56 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/OrganizationDto.java
> +    private File picture;
Вот например здесь ты будешь как раз таки передавать не `File`, а условный `PictureGetDto`, где будет то что я описал выше

2020-11-17 23:56 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/ProjectParticipationDto.java
> +    private User user;
Везде где ты передаешь вот так сущности напрямую, нужно передавать вместо них дтошки.
Например в этом случае у тебя бы утек логин и пароль в лапы к хацкерам.

2020-11-17 23:56 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/FileService.java
> +    FileDto createOrUpdate(FileDto fileDto);
У `Create` и `Update` наверняка будет разная логика в свое время. Я понимаю что сейчас это будет бойлерплейт, но зато потом придется меньше писать.

2020-11-17 23:56 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/OrganizationTypeServiceImpl.java
> +    @SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
Оно разве падает без этой штуки? Насколько я помню после первого запуска mapstruct генерирует свои классы и ворнинг пропадает, так что лучше убери.

2020-11-17 23:56 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/FileServiceImpl.java
> +        return fileStruct.toDto(fileRepository.findById(fileId).orElseThrow());
Отдавай лучше `null` в случаях, когда Optional пустой.

2020-11-18 00:23 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/ProjectParticipationDto.java
> +    private User user;
А пока лучше передавай чистые айдишники, там где `User` будет userId итд. Потом уже разберемся где какие данные нам нужны.

2020-11-18 00:24 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/OrganizationTypeServiceImpl.java
> +    @SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
Для мапстракта кстати есть классный плагин в идее, советую поставить

2020-11-18 00:25 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/FileServiceImpl.java
> +        return fileStruct.toDto(fileRepository.findById(fileId).orElseThrow());
Иначе мы просто утонем в эксепшенах. Да и ошибкой это сложно назвать, сущность то он дернул, кто виноват что ее там нет.

2020-11-18 00:28 UTC, Lixard commented
И еще, когда исправишь то что есть и нужен будет еще ревью, то в reviewers(справа от первого коммита) на мне нажми `Re-request review`, тогда мне уведомление прилетит и в самом гитхабе будет висеть что нужно посмотреть PR

2020-11-19 03:49 UTC, Lixard requested changes
В общем да, еще одна порция тредов 👼 . Проверь компилится ли оно вообще у тебя. Для того чтобы не забывать какие поля ты указал а какие нет у мапстракта есть плагин в идее, уже писал об этом.
И еще, когда ты исправляешь что-то, то закрывай старые треды(мои доебы до кода), там есть кнопочка `Resolve conservation` или что-то такое.

2020-11-19 03:49 UTC, Lixard commented on .gitignore
> +# See http://help.github.com/ignore-pictures/ for more about ignoring pictures.
Ржу, ты слишком капитально поменял `files` на `pictures`, задев то что не нужно было

2020-11-19 03:49 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/dto/PictureGetDto.java
> +public class PictureGetDto {
`Get` дтошки в `get` пэкедж

2020-11-19 03:49 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Слушай, а ты уверен, что оно вообще работает тут? У меня, например, не компилится ничего.
![image](https://user-images.githubusercontent.com/51443500/99618189-f1988200-2a31-11eb-981b-67421cba898d.png)

2020-11-19 03:49 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Так же у нас там стоят настройки, которые требуют явного указания какие поля ты будут `ignore`

2020-11-19 03:49 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/OrganizationServiceImpl.java
> +    public OrganizationServiceImpl(OrganizationRepository organizationRepository,
Поставь везде `@Autowired`

2020-11-19 03:49 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/OrganizationServiceImpl.java
> +    public OrganizationServiceImpl(OrganizationRepository organizationRepository,
Оно конечно и без этого умеет работать, но чем явнее указаны настройки, тем лучшее

2020-11-19 03:49 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationTypeStruct.java
> +public interface OrganizationTypeStruct {
Ну и до код-стайла доебусь 😇 , у всех интерфейсов в названии лучше делать I вначале. типа `IUserService`, а его имплементация `UserServiceImpl`

2020-11-19 03:52 UTC, Lixard requested changes
Еще чуть-чуть 😇

2020-11-19 03:52 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/UserServiceImpl.java
> +        return userStruct.toDto(userRepository.findById(userId).get());
И нет, не `get()`. Нужно что-то вида
```
userRepository.findById(userId).orElse(null);
```

2020-11-19 03:57 UTC, Lixard commented
И еще, я в твою ветку закинул коммит, подтяни его. Там для кодировки патч.

2020-11-19 04:14 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/UserServiceImpl.java
> +        return userStruct.toDto(userRepository.findById(userId).get());
гет кидает `NoSuchElementException` если опшионал будет пустым.

2020-11-19 13:31 UTC, Lixard commented on .gitignore
> +# See http://help.github.com/ignore-pictures/ for more about ignoring pictures.
Там ты еще несколько файлов задел, посмотри по дифу.

2020-11-19 17:23 UTC, PatcH11 commented on .gitignore
> +# See http://help.github.com/ignore-pictures/ for more about ignoring pictures.
Ахахахахаха

2020-11-21 15:32 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Есть, кстати, вероятность что эта проблема связана с ломбоком. Можешь попробовать без него сущности сделать. Но это только догадки)

2020-11-21 15:34 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Мне лично все равно на ломбок в проекте, чтобы сгенерить геттеры-сеттеры в идее нужно две кнопки нажать, так что не принципиально

2020-11-21 15:34 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Зато контроля будет больше, так как меньше магии

2020-11-21 15:35 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
щя попробую

2020-11-21 15:36 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
просто есть где ничего не надо мапить, а оно всё равно с ошибкой падает. типа не нашло на что сослаться

2020-11-21 15:41 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Потому что наоборот надо писать 🍭

2020-11-21 15:42 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Если ты вот здесь поменяешь местами source и target то оно заработает. Соурс - откуда берешь, target - куда кладешь
```
    @Mapping(source = "userId", target = "user.id")
    @Mapping(source = "organizationId", target = "organization.id")
    UserOrganizationDto toDto(UserOrganization userOrganization);
```

2020-11-21 15:43 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Куда кладешь - это то, что возвращает метод, откуда берешь - параметр

2020-11-21 15:43 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
И по код-стайлу правильней писать сначала таргет, а потом соурс. Тогда и путаницы не будет

2020-11-21 15:44 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
так я так и писал

2020-11-21 15:46 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
🤔 Ну вот этот пример выше я с твоей ветки взял

2020-11-21 15:48 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
То есть, то что выше - неправильно, нужно наоборот.

2020-11-21 15:49 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Оу, да, действительно так писал. Но потом поставил плагин и он ставит уже правильно

2020-11-21 15:52 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
хах, убрал бумбок и заработало, то что должно было заработать

2020-11-21 15:54 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Даже если ты оставишь как было? Странно, потому что ошибка в маппинге 🤔

2020-11-21 15:55 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Ну ломбок с мапстрактом из покон веков плохо дружит, хотя у меня получалось их дружить каким-то образом

2020-11-21 16:02 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
![image](https://user-images.githubusercontent.com/50721881/99881666-15271c80-2c2c-11eb-90b5-af1710e12741.png)

2020-11-21 16:05 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
я только бумбокс везде убрал) выкидываем его полность?

2020-11-21 16:09 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
или оставить чтобы он конструкторы с equalsHashcode генерил?

2020-11-21 16:14 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
Выпиливаем, equals и hashcode так же генерирует идея, alt+insert и там найдешь в списке

2020-11-21 16:15 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
У тебя гавно с маппингом только в UserOrganization как я понял, там сорс и таргет местами перепутаны

2020-11-21 16:16 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
То что оно компилится != что оно не будет выдавать null'ы по итогу

2020-11-21 16:19 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
просто в этом случае идея в том, что в UserOrganization нет такого поля как userId, а в дтошке нет user.id
![image](https://user-images.githubusercontent.com/51443500/99882009-59b3b780-2c2e-11eb-82a0-39e9b1c91f48.png)

2020-11-21 16:28 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
![image](https://user-images.githubusercontent.com/50721881/99882197-bebbdd00-2c2f-11eb-8d5b-a1cacb6a2ad3.png)

2020-11-21 16:28 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/OrganizationStruct.java
> +public interface OrganizationStruct {
да, похоже так и есть

2020-11-21 19:03 UTC, Lixard requested changes
Последние правочки и можно будет заливать

2020-11-21 19:03 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/UserStruct.java
> +    @Mapping(target = "picture", source = "pictureGetDto")
Блин, вот здесь фигня получается, при методах create/update нужно передавать целую вложенную сущность. Что совершенно не удобно. Сделай во вложенных сущностях просто `pictureId` плиз. Раз мы сделали `picture` отдельной таблицей, то у нас кроме картинок там ничего не будет, а значит нет смысла тащить мету за собой.

2020-11-21 19:03 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/OrganizationTypeServiceImpl.java
> +        return organizationTypeStruct.toDto(organizationType);
INF(инф пишется когда тред не требует изменений, просто держит в курсе): у нас на самом деле есть проблема с update методами, потому что мы позволяем внешним ресурсам перезаписывать вообще все поля сущности(что логически неправильно), но я думаю эти проблемы мы будем решать уже позже, сначала нужно написать основу.

2020-11-21 19:03 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/IPictureService.java
> +    List<PictureDto> getFiles();
Тут в джавадоке и в названии методов осталось `files` хотя это теперь `pictures`. Поменяй плиз, а то путанница.

2020-11-21 19:03 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/PictureServiceImpl.java
> +    public void remove(int fileId) {
Тут тоже `fileId`. Короче везде где найдешь поменяй

2020-11-21 21:06 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/UserStruct.java
> +    @Mapping(target = "picture", source = "pictureGetDto")
Короче в этой строке будет
```java
@Mapping(target = "picture.id", source = "pictureId")
```
И в других сущностях по шаблону

2020-11-21 22:59 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/service/implementation/OrganizationTypeServiceImpl.java
> +        return organizationTypeStruct.toDto(organizationType);
Так, не особо понял, мне нужно что-то в update поменять?

2020-11-21 22:59 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/UserStruct.java
> +    @Mapping(target = "picture", source = "pictureGetDto")
![image](https://user-images.githubusercontent.com/50721881/99889445-65bb6b80-2c66-11eb-9188-bedb2fa0e72f.png)

2020-11-21 23:00 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/UserStruct.java
> +    @Mapping(target = "picture", source = "pictureGetDto")
![image](https://user-images.githubusercontent.com/50721881/99889446-6d7b1000-2c66-11eb-84e2-6a232677b810.png)

2020-11-21 23:00 UTC, PatcH11 commented on backend/services/src/main/java/ru/matcher/services/mapstruct/UserStruct.java
> +    @Mapping(target = "picture", source = "pictureGetDto")
Вот так же надо?

2020-11-22 06:19 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/service/implementation/OrganizationTypeServiceImpl.java
> +        return organizationTypeStruct.toDto(organizationType);
Нет, если у треда вначале написано "INF:" то ничего делать не нужно

2020-11-22 06:20 UTC, Lixard commented on backend/services/src/main/java/ru/matcher/services/mapstruct/UserStruct.java
> +    @Mapping(target = "picture", source = "pictureGetDto")
Угу, и в обратную сторону то же самое

2020-11-22 11:11 UTC, Lixard approved these changes
👍

2020-11-22 11:12 UTC, merged