#38
Lixard/matcher pull request #6
Opened 2020-11-24 21:03 UTC by PatcH11

2020-11-27 19:09 UTC, Lixard requested changes

2020-11-27 19:09 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/OrganizationController.java
> +    OrganizationDto updateOrganization(@PathVariable int id,
Везде `int` нужно поменять на `Integer`. Второй используется в случаях когда переменная nullable. Если переменная не может быть null, то первый.

2020-11-27 19:09 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/OrganizationController.java
> +        path = "/organization",
`organizations` - пути лучше писать во множественном числе

2020-11-27 19:09 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/PictureController.java
> +    PictureDto createPicture(@RequestBody PictureDto pictureDto) {
неее, картинку ты точно вот так не получишь))
Файлы передаются с помощью `MultipartFile`,а чтобы узнать что это такое нужно смотреть как написан контроллер по той ссылке которую я кидал еще давно. (где было хранение файлов бд)

2020-11-27 19:09 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/PictureController.java
> +        return pictureService.findById(id);
Соответственно, здесь ты картинку точно не скачаешь. Картинки отдаются как `byte[]` с определенным аттачментом, который позволяет получателю определить набор байтов как какой-то файл. Опять же - вперед по мой давней ссылке.

2020-11-27 19:09 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/ProjectController.java
> +     * Удаленеи проекта.
🍻

2020-11-27 19:09 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/PictureController.java
> +import org.springframework.web.bind.annotation.*;
Особо на это не обращал внимания, но лучше вот так не делать никогда, а явно указывать какие импорты тебе нужны. Чтоб идея сама не враппила это дело в звездочки, нужно какие-то параметры в настройках поменять(уже не помню где они именно находятся),
У нас в проекте не критично, потому что мне в целом все равно, но чек-стайл на проектах с настроенным CI/CD обычно за это норм трахает.

2020-11-27 19:10 UTC, Lixard commented on backend/src/main/java/ru/matcher/rest/controller/OrganizationController.java
> +    OrganizationDto updateOrganization(@PathVariable int id,
Везде - это где стоит `@PathVariable`, а то увлечешься еще))))

2020-11-27 20:13 UTC, PatcH11 commented on backend/src/main/java/ru/matcher/rest/controller/OrganizationController.java
> +    OrganizationDto updateOrganization(@PathVariable int id,
😈

2020-12-17 00:10 UTC, Lixard approved these changes
LGTM!

2020-12-17 00:11 UTC, merged

2020-12-17 00:13 UTC, PatcH11 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rest-контроллеры для простых операций с сущностями](https://trello.com/c/Oxnvwqme/38-rest-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D0%B5%D1%80%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D1%85-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B9-%D1%81-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D1%8F%D0%BC%D0%B8)